### PR TITLE
Netty 5

### PR DESCRIPTION
**Pull request by hyperxpro**
-Work In Progress-

### CODE REVIEW

**Comment by hyperxpro** [comment]
It's not ready yet because I'm not able to understand the new `IoHandler` and how addresses will be retrieved. Need help.

@franz1981 @normanmaurer

**Comment by hyperxpro** [comment]
VM crashed while running the Example class.

[hs_err_pid14.log](https://github.com/netty/netty-incubator-transport-io_uring/files/8839597/hs_err_pid14.log)

**Comment by franz1981** [comment]
@hyperxpro given that we are now aiming to JDK 11, we can make use of VarHandler to perform actions vs the off-heap data; this should help preventing bad things to happen, like these 
On monday I can take a look and send PR to your branch if you wish

**Comment by violetagg** [comment]
@hyperxpro @franz1981 Should we revive this work? I'm also interested in having io_uring for Netty5 and I can try to help. :)

**Comment by normanmaurer** [comment]
@chrisvest and myself will pick this up...

**Comment by chrisvest** [comment]
I plan to start working on this next week 🤞

**Comment by chrisvest** [comment]
@hyperxpro I plan to do this in multiple smaller steps, so I'll close this and make new PRs that are a mix of new stuff, and changes pulled from this one.

**Pull request closed without merging**
