### PR TITLE
Fix netty test 4.1.68

### PR DESCRIPTION
**Pull request by HookWoods**
Hello, I just saw this morning this [(Pull Request)](https://github.com/netty/netty-incubator-transport-io_uring/pull/110)
I made this PR to try to fix the test since netty has changed JUnit version that add TestInfo and other change.
Based on Epoll test for the setupClientChannel part

Hope it will help.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@HookWoods I think you also want too change the netty version in pom.xml ?

**Comment by normanmaurer** [comment]
Basically adding the changes that were done here:

https://github.com/netty/netty-incubator-transport-io_uring/pull/110/files

**Comment by HookWoods** [comment]
I based my branch on yours, so this change are already present in the code
https://github.com/netty/netty-incubator-transport-io_uring/blob/8e0e950df3f377ae556d807a60df47dfffb3e2b8/pom.xml#L89

**Comment by HookWoods** [comment]
Ok, I Change the base branch since you closed your PR, so here it is.

**Comment by normanmaurer** [comment]
@HookWoods a thanks!

**Comment by normanmaurer** [comment]
@HookWoods did you sign our ICLA already ?

https://netty.io/s/icla

**Comment by HookWoods** [comment]
Nop, signing it rn

**Comment by HookWoods** [comment]
Done

**Comment by normanmaurer** [comment]
@HookWoods thanks a lot!

**Pull request merged**
